# Provides the Trusted Artifact Signer CLI binaries, rekor-cli and ec


FROM quay.io/redhat-user-workloads/rhtas-tenant/rekor/rekor-cli@sha256:5c56a63e98d90f6d6974dbb297dda9f1a0892aac46fbb4307b3b14b01cc758dc as rekor
FROM quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v04/cli-v04@sha256:8c766da37d73bf07ecdd9154b64a6525e4f5ed55321b4871dc370a31e488fd18 as ec

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:29790f898839e92c0554d031856e1770254f27e66af593fc088fbb7d3e5e298e

ENV APP_ROOT=/opt/app-root
WORKDIR $APP_ROOT/src/

RUN mkdir -p $APP_ROOT/src/clients/darwin && \
    mkdir -p $APP_ROOT/src/clients/linux && \
    mkdir -p $APP_ROOT/src/clients/windows

COPY --from=rekor /usr/local/bin/rekor_cli_darwin_amd64.gz      $APP_ROOT/src/clients/darwin/rekor-cli-amd64.gz
COPY --from=rekor /usr/local/bin/rekor_cli_darwin_arm64.gz      $APP_ROOT/src/clients/darwin/rekor-cli-arm64.gz
COPY --from=rekor /usr/local/bin/rekor_cli_linux_amd64.gz       $APP_ROOT/src/clients/linux/rekor-cli-amd64.gz
COPY --from=rekor /usr/local/bin/rekor_cli_linux_arm64.gz       $APP_ROOT/src/clients/linux/rekor-cli-arm64.gz
COPY --from=rekor /usr/local/bin/rekor_cli_linux_ppc64le.gz     $APP_ROOT/src/clients/linux/rekor-cli-ppc64le.gz
COPY --from=rekor /usr/local/bin/rekor_cli_linux_s390x.gz       $APP_ROOT/src/clients/linux/rekor-cli-s390x.gz
COPY --from=rekor /usr/local/bin/rekor_cli_windows_amd64.exe.gz $APP_ROOT/src/clients/windows/rekor-cli-amd64.gz

COPY --from=ec /usr/local/bin/ec_darwin_amd64.gz      $APP_ROOT/src/clients/darwin/ec-amd64.gz
COPY --from=ec /usr/local/bin/ec_darwin_arm64.gz      $APP_ROOT/src/clients/darwin/ec-arm64.gz
COPY --from=ec /usr/local/bin/ec_linux_amd64.gz       $APP_ROOT/src/clients/linux/ec-amd64.gz
COPY --from=ec /usr/local/bin/ec_linux_arm64.gz       $APP_ROOT/src/clients/linux/ec-arm64.gz
COPY --from=ec /usr/local/bin/ec_linux_ppc64le.gz     $APP_ROOT/src/clients/linux/ec-ppc64le.gz
COPY --from=ec /usr/local/bin/ec_linux_s390x.gz       $APP_ROOT/src/clients/linux/ec-s390x.gz
COPY --from=ec /usr/local/bin/ec_windows_amd64.exe.gz $APP_ROOT/src/clients/windows/ec-amd64.gz

LABEL \
      com.redhat.component="trusted-artifact-signer-serve-cli-container-re" \
      name="trusted-artifact-signer-serve-cli-container-re" \
      version="1.0.0" \
      summary="Red Hat serves Trusted Artifact Signer CLI binaries, rekor-cli and ec" \
      description="Serves Trusted Artifact Signer CLI binaries, rekor-cli and ec, from an HTTP server" \
      io.k8s.description="Serves Trusted Artifact Signer CLI binaries, rekor-cli and ec, from an HTTP server" \
      io.k8s.display-name="Red Hat serves Trusted Artifact Signer CLI binaries, rekor-cli and ec" \
      io.openshift.tags="rekor, ec, cli, rhtas, trusted, artifact, signer, sigstore" \
      maintainer="trusted-artifact-signer@redhat.com"
