# Provides the Trusted Artifact Signer CLI binaries, cosign and gitsign

FROM quay.io/redhat-user-workloads/rhtas-tenant/cli/cosign@sha256:1295e3268dce50b2c8eb79fc3273aebdd03cabc964fdeabf4a06369c7d684eff AS cosign
FROM quay.io/redhat-user-workloads/rhtas-tenant/cli/gitsign@sha256:5e4ae8d729afed06f04b00cf0958893ca6b79f3a4bed927043bf74bdd60ab152 AS gitsign

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:119ac25920c8bb50c8b5fd75dcbca369bf7d1f702b82f3d39663307890f0bf26
ENV APP_ROOT=/opt/app-root
WORKDIR $APP_ROOT/src/

RUN mkdir -p $APP_ROOT/src/clients/darwin && \
    mkdir -p $APP_ROOT/src/clients/linux && \
    mkdir -p $APP_ROOT/src/clients/windows

COPY --from=cosign /usr/local/bin/cosign-darwin-amd64.gz  $APP_ROOT/src/clients/darwin/cosign-amd64.gz
COPY --from=cosign /usr/local/bin/cosign-darwin-arm64.gz  $APP_ROOT/src/clients/darwin/cosign-arm64.gz
COPY --from=cosign /usr/local/bin/cosign-linux-amd64.gz   $APP_ROOT/src/clients/linux/cosign-amd64.gz
COPY --from=cosign /usr/local/bin/cosign-linux-arm64.gz   $APP_ROOT/src/clients/linux/cosign-arm64.gz
COPY --from=cosign /usr/local/bin/cosign-linux-ppc64le.gz $APP_ROOT/src/clients/linux/cosign-ppc64le.gz
COPY --from=cosign /usr/local/bin/cosign-linux-s390x.gz   $APP_ROOT/src/clients/linux/cosign-s390x.gz
COPY --from=cosign /usr/local/bin/cosign-windows-amd64.exe.gz $APP_ROOT/src/clients/windows/cosign-amd64.gz

COPY --from=gitsign /usr/local/bin/gitsign_cli_darwin_amd64.gz      $APP_ROOT/src/clients/darwin/gitsign-amd64.gz
COPY --from=gitsign /usr/local/bin/gitsign_cli_darwin_arm64.gz      $APP_ROOT/src/clients/darwin/gitsign-arm64.gz
COPY --from=gitsign /usr/local/bin/gitsign_cli_linux_amd64.gz       $APP_ROOT/src/clients/linux/gitsign-amd64.gz
COPY --from=gitsign /usr/local/bin/gitsign_cli_linux_arm64.gz       $APP_ROOT/src/clients/linux/gitsign-arm64.gz
COPY --from=gitsign /usr/local/bin/gitsign_cli_linux_ppc64le.gz     $APP_ROOT/src/clients/linux/gitsign-ppc64le.gz
COPY --from=gitsign /usr/local/bin/gitsign_cli_linux_s390x.gz       $APP_ROOT/src/clients/linux/gitsign-s390x.gz
COPY --from=gitsign /usr/local/bin/gitsign_cli_windows_amd64.exe.gz $APP_ROOT/src/clients/windows/gitsign-amd64.gz


LABEL \
      com.redhat.component="trusted-artifact-signer-serve-cli-container-cg" \
      name="trusted-artifact-signer-serve-cli-container-cg" \
      version="1.0.0" \
      summary="Red Hat serves Trusted Artifact Signer CLI binaries, cosign and gitsign" \
      description="Serves Trusted Artifact Signer CLI binaries, cosign and gitsign, from an HTTP server" \
      io.k8s.description="Serves Trusted Artifact Signer CLI binaries, cosign and gitsign, from an HTTP server" \
      io.k8s.display-name="Red Hat serves Trusted Artifact Signer CLI binaries, cosign and gitsign" \
      io.openshift.tags="cosign, gitsign, rhtas, trusted, artifact, signer, sigstore" \
      maintainer="trusted-artifact-signer@redhat.com"
