#
# Note about source containers:
# Due to the way this image is built, the source container for the image itself
# does not include the full set of sources for the cli tool binaries included in
# the image. The complete sources for each cli tool are available in the source
# containers for the images that the binaries are extracted from.
#
# You can find the source containers for each of the cli tools in the following
# locations:
#
# Rekor CLI
#   https://catalog.redhat.com/software/containers/detail/652976ecee3ec526235c8a56
#   docker://registry.redhat.io/rhtas-tech-preview/rekor-cli-rhel9
#
# Enterprise Contract
#  https://catalog.redhat.com/software/containers/detail/65a0454ad3407c4a7825b10c
#  docker://registry.redhat.io/rhtas-tech-preview/ec-rhel9
##

# An image with oc so we can run `oc image extract` to download the binaries
FROM registry.redhat.io/openshift4/ose-tools-rhel8:v4.11.0-202401122348.p0.gbf40a6c.assembly.stream AS downloads

ARG REKOR_IMAGE=quay.io/redhat-user-workloads/rhtas-tenant/rekor/rekor-cli@sha256:eba81f448cb8463ef22d4320ccd39fcd12885041e704949fe4ee04fe9d471a11
ARG EC_IMAGE=quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v01-alpha/cli-v01-alpha@sha256:6aca9b2e9fde177d1398820b4b0609865dc2b0573c2d9e6d475e515a6a123f1c

RUN mkdir -p /downloads/rekor && \
    mkdir -p /downloads/ec

RUN oc image extract ${REKOR_IMAGE}   --path /usr/local/bin/rekor_cli_*:/downloads/rekor && \
    oc image extract ${EC_IMAGE}      --path /usr/local/bin/ec_*:/downloads/ec

FROM registry.access.redhat.com/ubi9/httpd-24@sha256:965f7b03ae8f45228bad765ce47bc8956711e854213df0e4cee8623d51317b0a

RUN mkdir -p /var/www/html/clients/darwin && \
    mkdir -p /var/www/html/clients/linux && \
    mkdir -p /var/www/html/clients/windows

COPY --from=downloads /downloads/rekor/rekor_cli_darwin_amd64.gz      /var/www/html/clients/darwin/rekor-cli-amd64.gz
COPY --from=downloads /downloads/rekor/rekor_cli_darwin_arm64.gz      /var/www/html/clients/darwin/rekor-cli-arm64.gz
COPY --from=downloads /downloads/rekor/rekor_cli_linux_amd64.gz       /var/www/html/clients/linux/rekor-cli-amd64.gz
COPY --from=downloads /downloads/rekor/rekor_cli_linux_arm64.gz       /var/www/html/clients/linux/rekor-cli-arm64.gz
COPY --from=downloads /downloads/rekor/rekor_cli_linux_ppc64le.gz     /var/www/html/clients/linux/rekor-cli-ppc64le.gz
COPY --from=downloads /downloads/rekor/rekor_cli_linux_s390x.gz       /var/www/html/clients/linux/rekor-cli-s390x.gz
COPY --from=downloads /downloads/rekor/rekor_cli_windows_amd64.exe.gz /var/www/html/clients/windows/rekor-cli-amd64.gz

COPY --from=downloads /downloads/ec/ec_darwin_amd64.gz      /var/www/html/clients/darwin/ec-amd64.gz
COPY --from=downloads /downloads/ec/ec_darwin_arm64.gz      /var/www/html/clients/darwin/ec-arm64.gz
COPY --from=downloads /downloads/ec/ec_linux_amd64.gz       /var/www/html/clients/linux/ec-amd64.gz
COPY --from=downloads /downloads/ec/ec_linux_arm64.gz       /var/www/html/clients/linux/ec-arm64.gz
COPY --from=downloads /downloads/ec/ec_linux_ppc64le.gz     /var/www/html/clients/linux/ec-ppc64le.gz
COPY --from=downloads /downloads/ec/ec_linux_s390x.gz       /var/www/html/clients/linux/ec-s390x.gz
COPY --from=downloads /downloads/ec/ec_windows_amd64.exe.gz /var/www/html/clients/windows/ec-amd64.gz

CMD run-httpd

LABEL \
      com.redhat.component="trusted-artifact-signer-serve-cli-container-re" \
      name="trusted-artifact-signer-serve-cli-container-re" \
      version="0.0.1" \
      summary="Red Hat serves Trusted Artifact Signer CLI binaries, rekor-cli and ec" \
      description="Serves Trusted Artifact Signer CLI binaries, rekor-cli and ec, from an HTTP server" \
      io.k8s.description="Serves Trusted Artifact Signer CLI binaries, rekor-cli and ec, from an HTTP server" \
      io.k8s.display-name="Red Hat serves Trusted Artifact Signer CLI binaries, rekor-cli and ec" \
      io.openshift.tags="rekor, ec, cli, rhtas, trusted, artifact, signer, sigstore" \
      maintainer="trusted-artifact-signer@redhat.com"
